---
- name: Test sap_system_state module
  hosts: geuw1-lsap1
  gather_facts: false

  tasks:

    - name: "Start or Stop SAP system"
      community.sap_libs.sap_system_state:
        sysnr: "00"
        state: stopped
        wait_timeout: 600
      become: true
      register: result_start

    - name: "Afficher résultat start"
      ansible.builtin.debug:
        var: result_start
